export default [
  require('../assets/image/bg_1.png'),
  require('../assets/image/bg_2.png'),
  require('../assets/image/woman_unchecked.png'),
  require('../assets/image/woman_checked.png'),
  require('../assets/image/return_name.png'),
  require('../assets/image/finger_mark.png'),
  require('../assets/image/man_checked.png'),
  require('../assets/image/home_page_start.png'),
  require('../assets/image/home_page.png'),
  require('../assets/image/letter_card.png'),
  require('../assets/image/man_unchecked.png'),
  require('../assets/image/more_btn.png'),
  require('../assets/image/pay_bg.png'),
  require('../assets/image/pay_close.png'),
  require('../assets/image/pay_success.png'),
]